routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register'=>false]);
// Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::resource('/users', 'UserController')->middleware('auth');
Route::resource('/cottage-types', 'CottageTypeController')->middleware('auth');
Route::resource('/cottages', 'CottageController')->middleware('auth');
Route::resource('/customers', 'CustomerController')->middleware('auth');
Route::resource('/customer-kyc', 'CustomerKycController')->middleware('auth');
Route::resource('/addons', 'AddonController')->middleware('auth');
Route::resource('/bookings', 'BookingController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/amenities', 'AmenitiesController')->middleware('auth');

app/Cottage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cottage extends Model
{
    protected $fillable = ['building_id','cottage_type_id'];
    public function cottage_type()
    {
        return $this->belongsTo("App\CottageType");
    }
}

app/CottageType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CottageType extends Model
{
    protected $fillable = ['name','rooms','max_children','max_adults','share_percentage','cost','gst'];
    protected $casts = [
        'name' => 'string',
        'rooms' => 'numeric',
        'max_adults' => 'numeric',
        'max_children' => 'numeric',
        'share_percentage' => 'float',
        'cost' => 'float',
        'gst' => 'float',
    ];
    public function amenities()
    {
        return $this->belongsToMany('App\Amenities','cottage_type_amenities');
    }
}

app/Http/Controllers/CottageController.php
<?php

namespace App\Http\Controllers;

use App\Cottage;
use Illuminate\Http\Request;

class CottageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cottages = Cottage::paginate();
        return view('cottages.index',['cottages'=>$cottages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cottageTypes = \App\CottageType::all();
        return view('cottages.create',['cottageTypes'=>$cottageTypes]);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "building_id"=>"required|string|unique:cottages",
            "cottage_type_id" => "required|string|exists:cottage_types,id",
        ]);
        $cottage = Cottage::create([
            'building_id'  => $request->building_id,
            'cottage_type_id' => $request->cottage_type_id,         
        ]);
        if($cottage){
            return redirect()->route('cottages.index')->with(['success'=>__('cottages.messages.cottage_created')]);
        }
        else{
            return redirect()->back()->with(['error'=>__('cottages.messages.unable_to_create_cottage')]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function show(Cottage $cottage)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function edit(Cottage $cottage)
    {
        $cottageTypes = \App\CottageType::all();
        return view('cottages.edit',['cottageTypes'=>$cottageTypes,'cottage'=>$cottage]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cottage $cottage)
    {
        $request->validate([
            "building_id"=>"required|string|unique:cottages,building_id,".$cottage->id,
            "cottage_type_id" => "required|string|exists:cottage_types,id",
        ]);
        $cottage->update([
            'building_id'  => $request->building_id,
            'cottage_type_id' => $request->cottage_type_id,
        ]);
        if($cottage){
            return redirect()->route('cottages.index')->with(['success'=>__('cottages.messages.cottage_updated')]);
        }
        else{
            return redirect()->back()->with(['error'=>__('cottages.messages.unable_to_update_cottage')]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cottage $cottage)
    {
        //
    }
}

resources/views/cottages/create.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('cottages.index')}}" class="btn btn-sm btn-light">@lang('general.back')</a>
    </div>
    <h2 class="font-weight-light">@lang('general.add_new') {{trans_choice('cottages.cottage',1)}}</h2>
</div>
<form method="POST" action="{{route('cottages.store')}}">
    @csrf
<table class="table table-sm table-bordered">
    <tbody>
        <tr>
            <th class="w-25">@lang('cottages.building_id')</th>
            <td>
                <input type="text" name="building_id" id="building_id" class="form-control form-control-sm @error('building_id') is-invalid @enderror" value="{{old('building_id')}}" autocomplete="OFF"/>
                @error('building_id')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>{{trans_choice('cottage_types.cottage_type',1)}}</th>
            <td>
                <select  name="cottage_type_id" id="cottage_type_id" class="form-control form-control-sm @error('cottage_type_id') is-invalid @enderror" value="{{old('cottage_type_id')}}" autocomplete="OFF">
                    <option selected disabled>--Select Cottage Type--</option>
                    @forelse ($cottageTypes as $cottageType)
                        <option {{old('cottage_type_id') == $cottageType->id ? "selected":''}} value="{{$cottageType->id}}">{{$cottageType->name}}</option>
                    @empty
                    @endforelse
                </select>
                @error('cottage_type_id')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
    </tbody>
</table>
<div class="container">
    <div class="float-right">
        <button type="submit" class="btn btn-success">@lang('general.save')</button>
    </div>
</div>
</form>

@endsection

resources/views/cottages/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('cottages.index')}}" class="btn btn-sm btn-light">@lang('general.back')</a>
    </div>
    <h2 class="font-weight-light">@lang('general.update') {{trans_choice('cottages.cottage',1)}} : {{$cottage->building_id}}</h2>
</div>
<form method="POST" action="{{route('cottages.update',$cottage)}}">
    @method('PUT')
    @csrf
<table class="table table-sm table-bordered">
    <tbody>
        <tr>
            <th class="w-25">@lang('cottages.building_id')</th>
            <td>
                <input type="text" name="building_id" id="building_id" class="form-control form-control-sm @error('building_id') is-invalid @enderror" value="{{old('building_id',$cottage->building_id)}}" autocomplete="OFF"/>
                @error('building_id')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>{{trans_choice('cottage_types.cottage_type',1)}}</th>
            <td>
                <select  name="cottage_type_id" id="cottage_type_id" class="form-control form-control-sm @error('cottage_type_id') is-invalid @enderror" value="{{old('cottage_type_id')}}" autocomplete="OFF">
                    <option selected disabled>--Select Cottage Type--</option>
                    @forelse ($cottageTypes as $cottageType)
                        <option {{old('cottage_type_id',$cottage->cottage_type_id) == $cottageType->id ? "selected":''}} value="{{$cottageType->id}}">{{$cottageType->name}}</option>
                    @empty
                    @endforelse
                </select>
                @error('cottage_type_id')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
    </tbody>
</table>
<div class="container">
    <div class="float-right">
        <button type="submit" class="btn btn-info">@lang('general.update')</button>
    </div>
</div>
</form>

@endsection

resources/views/cottages/index.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('cottages.create')}}" class="btn btn-sm btn-light">@lang('general.add_new') {{trans_choice('cottages.cottage',1)}}</a>
    </div>
    <h2 class="font-weight-light">{{trans_choice('cottages.cottage',2)}}</h2>
</div>
<table class="table table-sm table-bordered text-center">
    <thead>
        <tr>
            <th>@lang('cottages.building_id')</th>
            <th>{{trans_choice('cottage_types.cottage_type',1)}}</th>
            <th>@lang('cottage_types.rooms')</th>
            <th>@lang('cottage_types.max_children')</th>
            <th>@lang('cottage_types.max_adults')</th>
            <th>@lang('cottage_types.share_percentage')</th>
            <th>@lang('cottage_types.cost')</th>
            <th>@lang('cottage_types.gst')</th>
            <th>{{trans_choice('amenities.amenity',2)}}</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($cottages as $cottage)
        <tr>
            <td><a href="{{route('cottages.edit',$cottage)}}">{{$cottage->building_id}}</a></td>
            <td><a href="{{route('cottage-types.edit',$cottage->cottage_type)}}">{{$cottage->cottage_type->name}}</a></td>
            <td>{{$cottage->cottage_type->rooms}}</td>
            <td>{{$cottage->cottage_type->max_children}}</td>
            <td>{{$cottage->cottage_type->max_adults}}</td>
            <td>{{$cottage->cottage_type->share_percentage}}%</td>
            <td>{{$cottage->cottage_type->cost}}</td>
            <td>{{$cottage->cottage_type->gst}}%</td>
            <td>{{$cottage->cottage_type->amenities->pluck('name')->implode(', ')}}</td>
        </tr>
        @empty
            <td colspan="8" class="text-center">@lang('cottages.warnings.no_cottages_added')</td>
        @endforelse
    </tbody>
</table>
{{$cottages->links()}}
@endsection