routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register'=>false]);
// Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::resource('/users', 'UserController')->middleware('auth');
Route::resource('/cottage-types', 'CottageTypeController')->middleware('auth');
Route::resource('/cottages', 'CottageController')->middleware('auth');
Route::resource('/customers', 'CustomerController')->middleware('auth');
Route::resource('/customer-kyc', 'CustomerKycController')->middleware('auth');
Route::resource('/addons', 'AddonController')->middleware('auth');
Route::resource('/bookings', 'BookingController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/amenities', 'AmenitiesController')->middleware('auth');

app/Cottage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cottage extends Model
{
    protected $fillable = ['building_id','cottage_type_id'];
    public function cottage_type()
    {
        return $this->belongsTo("App\CottageType");
    }
}

app/CottageType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CottageType extends Model
{
    protected $fillable = ['name','rooms','max_children','max_adults','share_percentage','cost','gst'];
    protected $casts = [
        'name' => 'string',
        'rooms' => 'numeric',
        'max_adults' => 'numeric',
        'max_children' => 'numeric',
        'share_percentage' => 'float',
        'cost' => 'float',
        'gst' => 'float',
    ];
    public function amenities()
    {
        return $this->belongsToMany('App\Amenities','cottage_type_amenities');
    }
}

app/Http/Controllers/CottageController.php
<?php

namespace App\Http\Controllers;

use App\Cottage;
use Illuminate\Http\Request;

class CottageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cottages = Cottage::paginate();
        return view('cottages.index',['cottages'=>$cottages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cottageTypes = \App\CottageType::all();
        return view('cottages.create',['cottageTypes'=>$cottageTypes]);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "building_id"=>"required|string|unique:cottages",
            "cottage_type_id" => "required|string|exists:cottage_types,id",
        ]);
        $cottage = Cottage::create([
            'building_id'  => $request->building_id,
            'cottage_type_id' => $request->cottage_type_id,         
        ]);
        if($cottage){
            return redirect()->route('cottages.index')->with(['success'=>__('cottages.messages.cottage_created')]);
        }
        else{
            return redirect()->back()->with(['error'=>__('cottages.messages.unable_to_create_cottage')]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function show(Cottage $cottage)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function edit(Cottage $cottage)
    {
        $cottageTypes = \App\CottageType::all();
        return view('cottages.edit',['cottageTypes'=>$cottageTypes,'cottage'=>$cottage]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cottage $cottage)
    {
        $request->validate([
            "building_id"=>"required|string|unique:cottages,building_id,".$cottage->id,
            "cottage_type_id" => "required|string|exists:cottage_types,id",
        ]);
        $cottage->update([
            'building_id'  => $request->building_id,
            'cottage_type_id' => $request->cottage_type_id,
        ]);
        if($cottage){
            return redirect()->route('cottages.index')->with(['success'=>__('cottages.messages.cottage_updated')]);
        }
        else{
            return redirect()->back()->with(['error'=>__('cottages.messages.unable_to_update_cottage')]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cottage $cottage)
    {
        //
    }
}

resources/views/cottages/types/create.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('cottage-types.index')}}" class="btn btn-sm btn-light">@lang('general.back')</a>
    </div>
    <h2 class="font-weight-light">@lang('general.add_new') {{trans_choice('cottage_types.cottage_type',1)}}</h2>
</div>
<form method="POST" action="{{route('cottage-types.store')}}">
    @csrf
<table class="table table-sm table-bordered">
    <tbody>
        <tr>
            <th class="w-25">@lang('cottage_types.name')</th>
            <td>
                <input type="text" name="name" id="name" class="form-control form-control-sm @error('name') is-invalid @enderror" value="{{old('name')}}" autocomplete="OFF"/>
                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('cottage_types.rooms')</th>
            <td>
                <input type="number" step="1"  name="rooms" id="rooms" class="form-control form-control-sm @error('rooms') is-invalid @enderror" value="{{old('rooms')}}" autocomplete="OFF"/>
                @error('rooms')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('cottage_types.max_children')</th>
            <td>
                <input type="number" step="1"  name="max_children" id="max_children" class="form-control form-control-sm @error('max_children') is-invalid @enderror" value="{{old('max_children')}}" autocomplete="OFF"/>
                @error('max_children')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('cottage_types.max_adults')</th>
            <td>
                <input type="number" step="1"  name="max_adults" id="max_adults" class="form-control form-control-sm @error('max_adults') is-invalid @enderror" value="{{old('max_adults')}}" autocomplete="OFF"/>
                @error('max_adults')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('cottage_types.share_percentage')</th>
            <td>
                <input type="number" max="100" step="0.01" name="share_percentage" id="share_percentage" class="form-control form-control-sm @error('share_percentage') is-invalid @enderror" value="{{old('share_percentage')}}" autocomplete="OFF"/>
                @error('share_percentage')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('cottage_types.cost')</th>
            <td>
                <input type="number" step="0.01"  name="cost" id="cost" class="form-control form-control-sm @error('cost') is-invalid @enderror" value="{{old('cost')}}" autocomplete="OFF"/>
                @error('cost')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('cottage_types.gst')</th>
            <td>
                <input type="number" max="100" step="0.01" name="gst" id="gst" class="form-control form-control-sm @error('gst') is-invalid @enderror" value="{{old('gst')}}" autocomplete="OFF"/>
                @error('gst')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('amenities.amenity')</th>
            <td>
                @foreach ($amenities as $amenity)
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" {{in_array($amenity->id,old('amenities',[])) ? "checked":'' }} id="amenity-{{$amenity->id}}" value="{{$amenity->id}}" name="amenities[]">
                    <label class="custom-control-label" for="amenity-{{$amenity->id}}">{{$amenity->name}}</label>
                </div>
                @endforeach
                @error('amenities')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </td>
        </tr>    
    </tbody>
</table>
<div class="container">
    <div class="float-right">
        <button type="submit" class="btn btn-success">@lang('general.save')</button>
    </div>
</div>
</form>

@endsection

resources/views/cottages/types/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('cottage-types.index')}}" class="btn btn-sm btn-light">@lang('general.back')</a>
    </div>
    <h2 class="font-weight-light">@lang('general.edit') {{trans_choice('cottage_types.cottage_type',1)}} : {{$cottageType->name}}</h2>
</div>
<form method="POST" action="{{route('cottage-types.update',$cottageType)}}">
    @method("PUT")
    @csrf
<table class="table table-sm table-bordered">
    <tbody>
        <tr>
            <th class="w-25">@lang('cottage_types.name')</th>
            <td>
                <input type="text" name="name" id="name" class="form-control form-control-sm @error('name') is-invalid @enderror" value="{{old('name',$cottageType->name)}}" autocomplete="OFF"/>
                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>@lang('cottage_types.rooms')</th>
            <td>
                <input type="number" step="1"  name="rooms" id="rooms" class="form-control form-control-sm @error('rooms') is-invalid @enderror" value="{{old('rooms',$cottageType->rooms)}}" autocomplete="OFF"/>
                @error('rooms')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>@lang('cottage_types.max_children')</th>
            <td>
                <input type="number" step="1"  name="max_children" id="max_children" class="form-control form-control-sm @error('max_children') is-invalid @enderror" value="{{old('max_children',$cottageType->max_children)}}" autocomplete="OFF"/>
                @error('max_children')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>@lang('cottage_types.max_adults')</th>
            <td>
                <input type="number" step="1"  name="max_adults" id="max_adults" class="form-control form-control-sm @error('max_adults') is-invalid @enderror" value="{{old('max_adults',$cottageType->max_adults)}}" autocomplete="OFF"/>
                @error('max_adults')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>@lang('cottage_types.share_percentage')</th>
            <td>
                <input type="number" max="100" step="0.01" name="share_percentage" id="share_percentage" class="form-control form-control-sm @error('share_percentage') is-invalid @enderror" value="{{old('share_percentage',$cottageType->share_percentage)}}" autocomplete="OFF"/>
                @error('share_percentage')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>@lang('cottage_types.cost')</th>
            <td>
                <input type="number" step="0.01"  name="cost" id="cost" class="form-control form-control-sm @error('cost') is-invalid @enderror" value="{{old('cost',$cottageType->cost)}}" autocomplete="OFF"/>
                @error('cost')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>@lang('cottage_types.gst')</th>
            <td>
                <input type="number" max="100" step="0.01" name="gst" id="gst" class="form-control form-control-sm @error('gst') is-invalid @enderror" value="{{old('gst',$cottageType->gst)}}" autocomplete="OFF"/>
                @error('gst')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
        <tr>
            <th>@lang('amenities.amenity')</th>
            <td>
                @foreach ($amenities as $amenity)
                <div class="custom-control custom-checkbox">
                    <input type="checkbox" class="custom-control-input" {{in_array($amenity->id,old('amenities',$cottageType->amenities->pluck('id')->toArray())) ? "checked":'' }} id="amenity-{{$amenity->id}}" value="{{$amenity->id}}" name="amenities[]">
                    <label class="custom-control-label" for="amenity-{{$amenity->id}}">{{$amenity->name}}</label>
                </div>
                @endforeach
                @error('amenities')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </td>
        </tr>        
    </tbody>
</table>
<div class="container">
    <div class="float-right">
        <button type="submit" class="btn btn-info">@lang('general.update')</button>
    </div>
</div>
</form>

@endsection

resources/views/cottages/types/index.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('cottage-types.create')}}" class="btn btn-sm btn-light">@lang('general.add_new') {{trans_choice('cottage_types.cottage_type',1)}}</a>
    </div>
    <h2 class="font-weight-light">{{trans_choice('cottage_types.cottage_types',2)}}</h2>
</div>
<table class="table table-sm table-bordered text-center">
    <thead>
        <tr>
            <th>@lang('cottage_types.name')</th>
            <th>@lang('cottage_types.rooms')</th>
            <th>@lang('cottage_types.max_children')</th>
            <th>@lang('cottage_types.max_adults')</th>
            <th>@lang('cottage_types.share_percentage')</th>
            <th>@lang('cottage_types.cost')</th>
            <th>@lang('cottage_types.gst')</th>
            <th>{{trans_choice('amenities.amenity',2)}}</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($cottageTypes as $cottageType)
        <tr>
            <td><a href="{{route('cottage-types.edit',$cottageType)}}">{{$cottageType->name}}</a></td>
            <td>{{$cottageType->rooms}}</td>
            <td>{{$cottageType->max_children}}</td>
            <td>{{$cottageType->max_adults}}</td>
            <td>{{$cottageType->share_percentage}}%</td>
            <td>{{$cottageType->cost}}</td>
            <td>{{$cottageType->gst}}%</td>
            <td>{{$cottageType->amenities->pluck('name')->implode(', ')}}</td>
        </tr>
        @empty
            <td colspan="8" class="text-center">@lang('cottage_types.warnings.no_cottage_types_added')</td>
        @endforelse
    </tbody>
</table>
{{$cottageTypes->links()}}
@endsection