routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register'=>false]);
// Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::resource('/users', 'UserController')->middleware('auth');
Route::resource('/cottage-types', 'CottageTypeController')->middleware('auth');
Route::resource('/cottages', 'CottageController')->middleware('auth');
Route::resource('/customers', 'CustomerController')->middleware('auth');
Route::resource('/customer-kyc', 'CustomerKycController')->middleware('auth');
Route::resource('/addons', 'AddonController')->middleware('auth');
Route::resource('/bookings', 'BookingController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/amenities', 'AmenitiesController')->middleware('auth');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:ital,wght@0,300;0,700;1,300&display=swap" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app" class="bg-grey">
    <div class="container bg-white vh-100 px-0">
        <nav class="navbar navbar-expand-md navbar-dark bg-primary border-0 py-0">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            @include('layouts.authnav')
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        <main>
            @yield('content')
        </main>
    </div>
    </div>
</body>
</html>

resources/views/layouts/authnav.blade.php
<li class="nav-item dropdown">
    <a id="cottageDropDown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        Cottages
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="cottageDropDown">
        <a class="dropdown-item" href="{{ route('cottages.index') }}">All Cottages</a>
        <a class="dropdown-item" href="{{ route('cottages.create') }}">Add Cottage</a>
        <a class="dropdown-item" href="{{ route('cottage-types.index') }}">Cottage Types</a>
        <a class="dropdown-item" href="{{ route('cottage-types.create') }}">Add Cottage Types</a>
        <a class="dropdown-item" href="{{ route('amenities.index') }}">Amenities</a>
        <a class="dropdown-item" href="{{ route('amenities.create') }}">Add Amenity</a>
    </div>
</li>
<li class="nav-item dropdown">
    <a id="usersDropDown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        Users
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="usersDropDown">
        <a class="dropdown-item" href="{{ route('users.index') }}">All Users</a>
        <a class="dropdown-item" href="{{ route('users.create') }}">Add User</a>
    </div>
</li>
<li class="nav-item dropdown">
    <a id="customersDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        Customers
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="customersDropdown">
        <a class="dropdown-item" href="{{ route('customers.index') }}">All Customers</a>
        <a class="dropdown-item" href="{{ route('customers.create') }}">Add Customer</a>
        <a class="dropdown-item" href="{{ route('customer-kyc.index') }}">Kyc Documents</a>
    </div>
</li>
<li class="nav-item dropdown">
    <a id="bookingsDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
        Bookings
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="bookingsDropdown">
        <a class="dropdown-item" href="{{ route('bookings.index') }}">All Bookings</a>
        <a class="dropdown-item" href="{{ route('bookings.create') }}">Add Booking</a>
        <a class="dropdown-item" href="{{ route('transactions.index') }}">Transactions</a>
        <a class="dropdown-item" href="{{ route('transactions.create') }}">Add Transaction</a>
    </div>
</li>