routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['register'=>false]);
// Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@welcome')->name('welcome');
Route::resource('/users', 'UserController')->middleware('auth');
Route::resource('/cottage-types', 'CottageTypeController')->middleware('auth');
Route::resource('/cottages', 'CottageController')->middleware('auth');
Route::resource('/customers', 'CustomerController')->middleware('auth');
Route::resource('/customer-kyc', 'CustomerKycController')->middleware('auth');
Route::resource('/addons', 'AddonController')->middleware('auth');
Route::resource('/bookings', 'BookingController')->middleware('auth');
Route::resource('/transactions', 'TransactionController')->middleware('auth');
Route::resource('/amenities', 'AmenitiesController')->middleware('auth');

app/Cottage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cottage extends Model
{
    protected $fillable = ['building_id','cottage_type_id'];
    public function cottage_type()
    {
        return $this->belongsTo("App\CottageType");
    }
}

app/CottageType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CottageType extends Model
{
    protected $fillable = ['name','rooms','max_children','max_adults','share_percentage','cost','gst'];
    protected $casts = [
        'name' => 'string',
        'rooms' => 'numeric',
        'max_adults' => 'numeric',
        'max_children' => 'numeric',
        'share_percentage' => 'float',
        'cost' => 'float',
        'gst' => 'float',
    ];
    public function amenities()
    {
        return $this->belongsToMany('App\Amenities','cottage_type_amenities');
    }
}

app/Http/Controllers/AmenitiesController.php
<?php

namespace App\Http\Controllers;

use App\Amenities;
use Illuminate\Http\Request;

class AmenitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $amenities = Amenities::paginate();
        return view('cottages.amenities.index',['amenities'=>$amenities]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('cottages.amenities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "name"=>"required|string|max:255",
            "description" => "nullable|string",
        ]);
        $amenity = Amenities::create([
            'name'  => $request->name,
            'description' => $request->description,
        ]);
        if($amenity){
            return redirect()->route('amenities.index')->with(['success'=>__('general.messages.created',['type'=>"Amenity"])]);
        }
        else{
            return redirect()->back()->with(['error'=>__('general.messages.unable_to_create',['type'=>"Amenity"])]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Amenities  $amenities
     * @return \Illuminate\Http\Response
     */
    public function show(Amenities $amenity)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Amenities  $amenities
     * @return \Illuminate\Http\Response
     */
    public function edit(Amenities $amenity)
    {
        return view('cottages.amenities.edit',['amenity'=>$amenity]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Amenities  $amenities
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Amenities $amenity)
    {
        $request->validate([
            "name"=>"required|string|max:255",
            "description" => "nullable|string",
        ]);
        $amenity->update([
            'name'  => $request->name,
            'description' => $request->description,
        ]);
        if($amenity){
            return redirect()->route('amenities.index')->with(['success'=>__('general.messages.updated',['type'=>"Amenity"])]);
        }
        else{
            return redirect()->back()->with(['error'=>__('general.messages.unable_to_update',['type'=>"Amenity"])]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Amenities  $amenities
     * @return \Illuminate\Http\Response
     */
    public function destroy(Amenities $amenity)
    {
        //
    }
}

app/Http/Controllers/CottageController.php
<?php

namespace App\Http\Controllers;

use App\Cottage;
use Illuminate\Http\Request;

class CottageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cottages = Cottage::paginate();
        return view('cottages.index',['cottages'=>$cottages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cottageTypes = \App\CottageType::all();
        return view('cottages.create',['cottageTypes'=>$cottageTypes]);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            "building_id"=>"required|string|unique:cottages",
            "cottage_type_id" => "required|string|exists:cottage_types,id",
        ]);
        $cottage = Cottage::create([
            'building_id'  => $request->building_id,
            'cottage_type_id' => $request->cottage_type_id,         
        ]);
        if($cottage){
            return redirect()->route('cottages.index')->with(['success'=>__('cottages.messages.cottage_created')]);
        }
        else{
            return redirect()->back()->with(['error'=>__('cottages.messages.unable_to_create_cottage')]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function show(Cottage $cottage)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function edit(Cottage $cottage)
    {
        $cottageTypes = \App\CottageType::all();
        return view('cottages.edit',['cottageTypes'=>$cottageTypes,'cottage'=>$cottage]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Cottage $cottage)
    {
        $request->validate([
            "building_id"=>"required|string|unique:cottages,building_id,".$cottage->id,
            "cottage_type_id" => "required|string|exists:cottage_types,id",
        ]);
        $cottage->update([
            'building_id'  => $request->building_id,
            'cottage_type_id' => $request->cottage_type_id,
        ]);
        if($cottage){
            return redirect()->route('cottages.index')->with(['success'=>__('cottages.messages.cottage_updated')]);
        }
        else{
            return redirect()->back()->with(['error'=>__('cottages.messages.unable_to_update_cottage')]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Cottage  $cottage
     * @return \Illuminate\Http\Response
     */
    public function destroy(Cottage $cottage)
    {
        //
    }
}

resources/views/cottages/amenities/create.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('amenities.index')}}" class="btn btn-sm btn-light">@lang('general.back')</a>
    </div>
    <h2 class="font-weight-light">@lang('general.add_new') {{trans_choice('amenities.amenity',1)}}</h2>
</div>
<form method="POST" action="{{route('amenities.store')}}">
    @csrf
<table class="table table-sm table-bordered">
    <tbody>
        <tr>
            <th class="w-25">@lang('amenities.name')</th>
            <td>
                <input type="text" name="name" id="name" class="form-control form-control-sm @error('name') is-invalid @enderror" value="{{old('name')}}" autocomplete="OFF"/>
                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
            <th>@lang('amenities.description')</th>
            <td>
                <textarea name="description" id="description" class="form-control form-control-sm @error('description') is-invalid @enderror" value="{{old('description')}}" autocomplete="OFF" rows="10"></textarea>
                @error('description')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
    </tbody>
</table>
<div class="container">
    <div class="float-right">
        <button type="submit" class="btn btn-success">@lang('general.save')</button>
    </div>
</div>
</form>

@endsection

resources/views/cottages/amenities/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('cottage-types.index')}}" class="btn btn-sm btn-light">@lang('general.back')</a>
    </div>
    <h2 class="font-weight-light">@lang('general.edit') {{trans_choice('cottage_types.cottage_type',1)}} : {{$amenity->name}}</h2>
</div>
<form method="POST" action="{{route('amenities.update',$amenity)}}">
    @csrf
    @method('PUT')
<table class="table table-sm table-bordered">
    <tbody>
        <tr>
            <th class="w-25">@lang('amenities.name')</th>
            <td>
                <input type="text" name="name" id="name" class="form-control form-control-sm @error('name') is-invalid @enderror" value="{{old('name',$amenity->name)}}" autocomplete="OFF"/>
                @error('name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror
            </td>
        </tr>
            <th>@lang('amenities.description')</th>
            <td>
                <textarea name="description" id="description" class="form-control form-control-sm @error('description') is-invalid @enderror" autocomplete="OFF" rows="10">{{old('description',$amenity->description)}}</textarea>
                @error('description')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
                @enderror                
            </td>
        </tr>
    </tbody>
</table>
<div class="container">
    <div class="float-right">
        <button type="submit" class="btn btn-success">@lang('general.save')</button>
    </div>
</div>
</form>
@endsection

resources/views/cottages/amenities/index.blade.php
@extends('layouts.app')
@section('content')
<div class="py-4 px-4 text-light bg-primary">
    <div class="float-right">
        <a href="{{route('amenities.create')}}" class="btn btn-sm btn-light">@lang('general.add_new') {{trans_choice('amenities.amenity',1)}}</a>
    </div>
    <h2 class="font-weight-light">{{trans_choice('amenities.amenity',2)}}</h2>
</div>
<table class="table table-sm table-bordered text-center">
    <thead>
        <tr>
            <th>@lang('amenities.name')</th>
            <th>{{trans_choice('cottage_types.cottage_type',2 )}}</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($amenities as $amenity)
        <tr>
            <td><a href="{{route('amenities.edit',$amenity)}}">{{$amenity->name}}</a></td>
            <td>{{$amenity->cottage_types->pluck('name')->implode(',')}}</td>
        </tr>
        @empty
            <td colspan="8" class="text-center">@lang('amenities.warnings.no_amenities_added')</td>
        @endforelse
    </tbody>
</table>
{{$amenities->links()}}
@endsection